"""10_neiman_size_diagnostic.py

Neiman's (t_F - t_E) sample-size / time-averaging diagnostic (Neiman 1995:17)
applied to the basin neutrality signature, answering whether the empirical
neutrality-departure decline is a transmission signal or an aggregation/size
artifact. Reports per-assemblage t_F, t_E, the signed difference vs assemblage
size N, and whether N and richness k trend along the CA seriation axis. This
result supports the Supplemental Text discussion of the neutrality signature.

Writes output/neiman_size_diagnostic.md. Read-only on data; no manuscript edits.

Usage: python3 analyses/10_neiman_size_diagnostic.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "analyses"))

import matplotlib  # noqa: E402
matplotlib.use("Agg")
import make_figures as mf  # noqa: E402  (basin-restricted _load_curated, correspondence_axis)

OUT = ROOT / "output" / "neiman_size_diagnostic.md"


def neiman_size_diagnostic() -> list[str]:
    counts, _ = mf._load_curated()  # basin (53), 10 decorated types
    M = counts.to_numpy(float)
    N = M.sum(1)
    k = (M > 0).sum(1)
    tF = np.array([mf.theta_f(r) for r in M])
    tE = np.array([mf.theta_e(r) for r in M])
    fin = np.isfinite(tF) & np.isfinite(tE) & (tE > 0) & (N >= 2)
    ca1, _, _ = mf.correspondence_axis(M)
    rank = pd.Series(ca1).rank().to_numpy()

    def sp(a, b):
        r, p = spearmanr(a[fin], b[fin])
        return r, p

    L = ["## Neiman (1995:17) sample-size / time-averaging diagnostic", ""]
    L.append(f"Basin curated set: n = {fin.sum()} assemblages, 10 decorated types. "
             f"Assemblage size N: median {np.median(N):.0f}, range [{N.min():.0f}, {N.max():.0f}].")
    L.append("")
    L.append("| quantity | Spearman rho | p |")
    L.append("|---|---|---|")
    for lab, (a, b) in {
        "t_F vs N (size sensitivity of homozygosity estimator)": (tF, N),
        "t_E vs N (size sensitivity of richness estimator)": (tE, N),
        "(t_F - t_E) vs N  [Neiman's artifact diagnostic]": (tF - tE, N),
        "k (richness) vs N": (k.astype(float), N),
        "N vs CA-rank (does size trend along the axis?)": (N, rank),
        "k vs CA-rank (does richness trend along the axis?)": (k.astype(float), rank),
        "t_F vs CA-rank (size-sensitive theta level)": (tF, rank),
        "t_E vs CA-rank (size-robust theta level)": (tE, rank),
    }.items():
        r, p = sp(a, b)
        L.append(f"| {lab} | {r:+.2f} | {p:.3f} |")
    L += ["",
          "**Reading.** The signed estimator difference does not track assemblage size, "
          "so the aggregation artifact Neiman warns of is weak (as in his Woodland case). "
          "Assemblage size does trend with CA position, and the size-robust t_E shows no "
          "trend while the size-sensitive t_F declines, so part of the neutrality-departure "
          "decline reflects estimator size-sensitivity rather than a transmission change. "
          "The neutrality signature should be read cautiously; it is weaker than the binned "
          "departure trend alone implies, which reinforces the negative reading.", ""]
    return L


def main() -> None:
    lines = ["# Neiman sample-size / time-averaging diagnostic",
             "", "Generated by analyses/10_neiman_size_diagnostic.py.",
             ""]
    lines += neiman_size_diagnostic()
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
