"""phasecheck, stage 2: the copying model with no groups, its calibration, and what it can detect."""
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import phasecheck as pc
from phasecheck import copying as cp
from phasecheck import model as md
from phasecheck.cli import main as cli_main

ROOT = Path(__file__).resolve().parents[2]
EXAMPLE = ROOT / "examples" / "phasecheck" / "st_francis_basin.csv"
RIVER = ROOT / "examples" / "phasecheck" / "st_francis_river_km.csv"
PAPER_RATES = {"n_ind": 2000, "innovation": 0.001, "mixing": 0.02, "length": 24.0}


def test_the_model_is_the_papers_model():
    """Same weights, same frequencies, same sampled counts as the implementation the paper ran."""
    from mls_emergence.transmission import spatial as sp
    rng = np.random.default_rng(0)
    pts = rng.uniform(0, 80, (12, 2))
    d = np.sqrt(((pts[:, None] - pts[None]) ** 2).sum(-1))
    lab, tgt = np.repeat([0, 1, 2], 4), np.array([.5, .3, .15, .05])
    for leak in (1.0, 0.03):
        a, b = md.copying_weights(d, 24.0, lab, leak), sp.copying_weights(d, 24.0, labels=lab, leak=leak)
        ra = md.drift_record(a, k=4, n_ind=500, mixing=.02, innovation=.001, target=tgt, seed=7)
        rb = sp.drift_record(b, k=4, n_ind=500, mixing=.02, innovation=.001, seed=7, target=tgt)
        o, t = np.linspace(0, 1, 12), np.full(12, 200)
        assert np.array_equal(a, b) and np.array_equal(ra, rb)
        assert np.array_equal(md.sample_record(ra, o, t, np.random.default_rng(3)),
                              sp.sample_record(rb, o, t, np.random.default_rng(3)))


def test_a_restriction_lowers_copying_across_lines_only():
    """Direction. leak below 1 must reduce the share of copying that crosses a line, never raise it."""
    d = np.abs(np.subtract.outer(np.arange(6.0), np.arange(6.0))) * 10
    lab = np.repeat([0, 1], 3)
    cross = lambda w: float(w[lab[:, None] != lab[None, :]].sum())
    free, cut = md.copying_weights(d, 20.0, lab, 1.0), md.copying_weights(d, 20.0, lab, 0.03)
    assert cross(cut) < 0.2 * cross(free)
    assert np.allclose(free.sum(1), 1) and np.allclose(cut.sum(1), 1)
    with pytest.raises(ValueError, match="needs labels"):
        md.copying_weights(d, 20.0, None, 0.5)
    with pytest.raises(ValueError, match="positive"):
        md.copying_weights(d, 0.0)


def test_reproduces_the_papers_comparison_with_the_copying_model():
    """Expected values from output/findings/phase_profiles.md and phases_as_groups.md (analyses 99 and
    84), which run the paper's own implementation at the calibrated settings with these seeds."""
    data = pc.read_table(EXAMPLE, distance=RIVER, order_col="seriation_order")
    r = cp.compare_with_model(data, PAPER_RATES, reps=300, seed=84000)
    rows = {x["measure"]: x for x in r["rows"]}
    f = rows["cultural F_ST between the phases"]
    assert (round(f["observed"], 4), round(f["median"], 4), round(f["lo"], 4), round(f["hi"], 4)) == \
        (0.0123, 0.0024, 0.0006, 0.0116) and (f["reaching"], f["runs"]) == (7, 300)
    s = rows["sherds that would have to change class to make two phases alike, mean over pairs (percent)"]
    assert (round(s["observed"], 1), round(s["median"], 1), round(s["lo"], 1), round(s["hi"], 1)) == \
        (19.4, 7.4, 4.0, 13.2) and s["reaching"] == 0
    assert rows["sherds that would have to change class, Kent and Parkin (percent)"]["reaching"] == 17
    e = rows["boundary excess at the phase lines"]
    assert round(e["observed"], 1) == 7.7 and round(e["median"], 1) == 1.2      # both positive
    assert round(r["decay"]["observed"], 2) == -0.20                            # similarity falls with distance
    assert r["decay"]["lo"] < r["decay"]["observed"] < r["decay"]["hi"]


def _map(seed=11, n=24):
    rng = np.random.default_rng(seed)
    east, north = rng.uniform(0, 60, n), rng.uniform(0, 60, n)
    lat, lon = 35.0 + north / 111.32, -90.0 + east / (111.32 * np.cos(np.deg2rad(35.27)))
    phase = np.where(east < 20, "West", np.where(east < 40, "Mid", "East"))
    return lat, lon, phase


def _table(counts, lat, lon, phase, tmp_path, name):
    df = pd.DataFrame(counts, columns=[f"class_{j + 1}" for j in range(counts.shape[1])])
    df.insert(0, "phase", phase); df.insert(0, "longitude", lon); df.insert(0, "latitude", lat)
    df.insert(0, "name", [f"site_{i + 1:02d}" for i in range(len(df))])
    p = tmp_path / name
    df.to_csv(p, index=False)
    return pc.read_table(p)


RATES = {"n_ind": 500, "innovation": 0.004, "mixing": 0.02, "length": 12.0}


def _made_by_the_model(tmp_path, leak, seed=3):
    """A record generated by the copying model itself on a constructed map, with or without a restriction."""
    lat, lon, phase = _map()
    shell = _table(np.full((len(lat), 6), 50), lat, lon, phase, tmp_path, "shell.csv")
    shell.counts = np.random.default_rng(1).multinomial(300, [.35, .25, .18, .12, .06, .04], size=len(lat))
    m = cp.simulate(shell, RATES, seed, leak=leak)
    return _table(m, lat, lon, phase, tmp_path, f"made_{leak}.csv")


def test_model_comparison_tells_a_restricted_record_from_an_unrestricted_one(tmp_path):
    """The discriminating pair for question 7. A record made by the model with no groups must fall
    inside the model's own range; the same map with copying across the lines cut to 3 percent must
    stand above it. A comparison that always found an excess, or never did, fails one half."""
    free = cp.compare_with_model(_made_by_the_model(tmp_path, 1.0), RATES, reps=80, seed=500)["rows"][0]
    cut = cp.compare_with_model(_made_by_the_model(tmp_path, 0.03), RATES, reps=80, seed=500)["rows"][0]
    assert free["reaching"] / free["runs"] > 0.05
    assert cut["reaching"] / cut["runs"] < 0.05 and cut["observed"] > 3 * free["observed"]


def test_power_rises_with_the_restriction(tmp_path):
    """Records made with a restriction must score higher against alternative lines than records made
    without one. Equal scores would mean the comparison cannot detect what it is used to detect."""
    p = cp.power(_made_by_the_model(tmp_path, 1.0), RATES, records=60, n_alt=40, leaks=(1.0, 0.03), seed=900)
    free, cut = p["rows"]
    assert cut["around"][2] > free["around"][2] + 0.2          # medians
    assert 0 <= p["observed_around"] <= 1


def test_calibration_finds_the_settings_that_made_the_record_and_refuses_when_none_fit(tmp_path):
    data = _made_by_the_model(tmp_path, 1.0)
    grid = {"n_ind": (500,), "innovations": (0.0005, 0.004, 0.05), "mixings": (0.02, 0.4), "reps": 3,
            "confirm_reps": 12, "length": 12.0}
    c = cp.calibrate(data, **grid)
    assert c["n_confirmed"] >= 1 and c["rates"]["length"] == 12.0
    sel = c["table"][c["table"].selected].iloc[0]
    obs = cp.diversity(data.counts)
    assert abs(sel.sim_within - obs["within"]) / obs["within"] <= 0.10
    # the settings that made the record are among the confirmed ones
    made = c["table"][(c["table"].innovation == 0.004) & (c["table"].mixing == 0.02)].iloc[0]
    assert bool(made.confirmed)
    with pytest.raises(ValueError, match="no setting of the copying model reproduces"):
        cp.calibrate(data, **{**grid, "tolerance": 1e-6})


def test_order_column_places_assemblages_and_is_not_a_class(tmp_path):
    lat, lon, phase = _map()
    df = pd.DataFrame(np.random.default_rng(2).multinomial(200, [.5, .3, .2], size=len(lat)),
                      columns=["a", "b", "c"])
    df.insert(0, "date_ad", np.linspace(1350, 1550, len(lat))[::-1])
    df.insert(0, "phase", phase); df.insert(0, "longitude", lon); df.insert(0, "latitude", lat)
    df.insert(0, "name", [f"s{i}" for i in range(len(df))])
    p = tmp_path / "o.csv"; df.to_csv(p, index=False)
    data = pc.read_table(p, order_col="date_ad")
    assert data.classes == ["a", "b", "c"]
    assert data.order[0] == 1.0 and data.order[-1] == 0.0       # the latest date is 1, the earliest 0
    assert np.allclose(np.sort(data.order), np.linspace(0, 1, len(lat)))
    with pytest.raises(ValueError):
        pc.read_table(p)                                         # unnamed, the date column is refused


def test_command_line_with_supplied_rates_answers_the_model_questions(tmp_path):
    _made_by_the_model(tmp_path, 1.0)                    # writes made_1.0.csv, the table the command reads
    out = tmp_path / "rep"
    code = cli_main([str(tmp_path / "made_1.0.csv"), "--out", str(out), "--draws", "120", "--alternatives", "30",
                     "--rates", "500,0.004,0.02", "--length-km", "12", "--model-runs", "60"])
    text = (out / "report.md").read_text()
    assert code == 0 and (out / "model_comparison.csv").exists()
    for heading in ("## 6. Can copying with no groups reproduce this record's diversity?",
                    "## 7. Does the record differ between phases by more than copying across distance produces?",
                    "## 8. Would assemblages made with no groups sort into these phases?",
                    "## 9. Could this comparison detect a restriction at the phase boundaries?"):
        assert heading in text
    assert "This length is an assumption, not an estimate" in text


# ---------------------------------------------------------------- after the stage 2 review
def test_calibration_selects_the_largest_difference_among_those_that_fit(tmp_path):
    """The selection rule itself. Selecting the smallest instead would pass every other test here."""
    data = _made_by_the_model(tmp_path, 1.0)
    c = cp.calibrate(data, n_ind=(500,), innovations=(0.0005, 0.004, 0.05), mixings=(0.02, 0.4), reps=3,
                     confirm_reps=12, length=12.0)
    t = c["table"]
    ok = t[t.confirmed]
    assert len(ok) >= 2, "the rule needs at least two fitting settings to be tested"
    assert t[t.selected].fst_median.iloc[0] == ok.fst_median.max() > ok.fst_median.min()
    assert list(c["ranked"].fst_median) == sorted(ok.fst_median, reverse=True)


def test_calibration_reproduces_the_papers_on_its_record():
    """The paper (output/revision_2026_09/calibrated_rates.csv, analysis 47): 51 of 297 combinations
    matched, 48 confirmed, and 2,000 learners, innovation 0.001, mixing 0.02 selected by the difference
    between two spatial clusters. The clusters are rebuilt here as the paper built them."""
    import os

    from mls_emergence.signatures.assortativity import _kmeans_labels
    data = pc.read_table(EXAMPLE, distance=RIVER, order_col="seriation_order")
    xy = np.column_stack([data.lat, data.lon])
    two = _kmeans_labels(xy - xy.mean(0), 2, seed=7)
    c = cp.calibrate(data, length=24.0, select_labels=two, jobs=min(12, os.cpu_count() or 1))
    assert (c["n_matched"], c["n_confirmed"], c["n_cells"]) == (51, 48, 297)
    assert c["rates"] == {"n_ind": 2000, "innovation": 0.001, "mixing": 0.02, "length": 24.0}


def test_runs_that_lose_all_diversity_are_counted_not_dropped(tmp_path):
    """With no innovation a small population fixes on one class. Such runs show no difference between
    phases; leaving them out would keep only the runs that differ and overstate the model."""
    data = _made_by_the_model(tmp_path, 1.0)
    r = cp.compare_with_model(data, {"n_ind": 200, "innovation": 0.0, "mixing": 0.4, "length": 12.0}, reps=60, seed=10)
    f = r["rows"][0]
    assert r["flat"] > 0 and f["runs"] == 60          # every run stays in the count
    assert f["reaching"] <= 60 - r["flat"]            # a flat run cannot reach a positive difference
    with pytest.raises(ValueError, match="lost all diversity"):      # nearly every run flat: refused
        cp.compare_with_model(data, {"n_ind": 40, "innovation": 0.0, "mixing": 0.4, "length": 12.0}, reps=60, seed=10)


def _row(observed, lo, hi, reaching=10, runs=100):
    return {"observed": observed, "lo": lo, "hi": hi, "median": (lo + hi) / 2, "reaching": reaching, "runs": runs}


def test_question_7_is_read_from_both_sides():
    """Each reading must be true of the numbers that trigger it. The first version said the model
    'accounts for' a record that was LESS differentiated than every run."""
    from phasecheck.report import _reading_7
    r = {"n_ind": 1, "innovation": 0, "mixing": 0, "length": 1}
    above = _reading_7([("a", r, _row(0.05, 0.001, 0.02, 0))], True)
    below = _reading_7([("a", r, _row(0.0005, 0.004, 0.02, 100))], True)
    inside = _reading_7([("a", r, _row(0.01, 0.001, 0.02, 30))], True)
    mixed = _reading_7([("a", r, _row(0.01, 0.001, 0.02, 30)), ("b", r, _row(0.01, 0.0001, 0.004, 0))], True)
    assert "differ by more than the model" in above and "does not fit" not in above
    assert "differ by LESS" in below and "does not fit this record" in below and "can produce" not in below
    assert "inside the range" in inside and "can produce a difference of this size" in inside
    assert "depends on the setting" in mixed and "cannot say" in mixed
    # a record no setting shows to exceed the model is not "undecided": the model can account for it
    null = _reading_7([("a", r, _row(0.0003, 0.001, 0.02, 100)), ("b", r, _row(0.0003, 0.0001, 0.004, 40)),
                       ("c", r, _row(0.0003, 0.0001, 0.002, 30))], True)
    assert "At no setting tried" in null and "can produce a difference of this size" in null
    assert "cannot say" not in null and "do not fit it" in null
    supplied = _reading_7([("a", r, _row(0.01, 0.001, 0.02, 30))], False)
    assert "holds only if they fit" in supplied and "holds only if they fit" not in inside


def _pw(free_med, tight_med, free_low, tight_low, distinct_compact=20):
    row = lambda leak, med, low: {"leak": leak, "records": 100, "around": [0, 0, med, 1, 1],
                                  "compact": [0, 0, med, 1, 1], "around_at_or_below": low,
                                  "compact_at_or_below": low, "reach_fst": 0.1}
    return {"rows": [row(1.0, free_med, free_low), row(0.03, tight_med, tight_low)], "n_alt": 50,
            "observed_around": 0.5, "observed_compact": 0.5, "distinct_around": 40,
            "distinct_compact": distinct_compact, "same_as_phases_around": 0, "same_as_phases_compact": 0}


def test_question_9_is_read_from_the_numbers():
    from phasecheck.report import _reading_9, _share
    strong = _reading_9(_pw(0.4, 0.8, 0.7, 0.25))
    assert "strongly" in strong and "responds to a restriction" in strong and "weighs against one" in strong
    weak = _reading_9(_pw(0.5, 0.6, 0.55, 0.40))
    assert "slightly" in weak and "though weakly" in weak and "weighs weakly against one" in weak
    flat = _reading_9(_pw(0.5, 0.4, 0.5, 0.55))
    assert "cannot detect a restriction here" in flat and "responds to" not in flat
    assert "does not favor either" in flat
    for_one = _reading_9(_pw(0.4, 0.8, 0.02, 0.9))
    assert "weighs for one" in for_one and "0.0 to 1" not in for_one and "30.0 times" in for_one
    assert "lower bound" in _reading_9(_pw(0.4, 0.8, 0.6, 0.0))
    # direction: at_or_below of 0 for both means every simulated record scored ABOVE the real one
    lowest = _reading_9(_pw(0.4, 0.8, 0.0, 0.0))
    assert "scored above the real one" in lowest and "lower than either kind" in lowest and "higher than" not in lowest
    from phasecheck.report import _pct
    assert (_pct(1 / 300), _pct(0.0), _pct(0.25), _pct(3 / 1000)) == ("0.3", "0", "25", "0.3")
    assert "carries little weight" in _reading_9(_pw(0.4, 0.8, 0.7, 0.25, distinct_compact=2))
    assert _share(1, 300) == "1 of 300 (0.3%)" and _share(0, 300) == "none of 300" and _share(30, 300) == "30 of 300 (10%)"


def test_tied_order_values_share_a_position_whatever_the_row_order(tmp_path):
    lat, lon, phase = _map()
    df = pd.DataFrame(np.random.default_rng(2).multinomial(200, [.5, .3, .2], size=len(lat)), columns=["a", "b", "c"])
    df.insert(0, "period", np.repeat([1, 2, 3], len(lat) // 3))
    df.insert(0, "phase", phase); df.insert(0, "longitude", lon); df.insert(0, "latitude", lat)
    df.insert(0, "name", [f"s{i}" for i in range(len(df))])
    p1, p2 = tmp_path / "a.csv", tmp_path / "b.csv"
    df.to_csv(p1, index=False); df.iloc[::-1].to_csv(p2, index=False)
    a, b = pc.read_table(p1, order_col="period"), pc.read_table(p2, order_col="period")
    assert len(set(np.round(a.order, 9))) == 3
    assert dict(zip(a.names, a.order)) == dict(zip(b.names, b.order))


def test_run_counts_that_would_reuse_seeds_are_refused(tmp_path):
    data = _made_by_the_model(tmp_path, 1.0)
    with pytest.raises(ValueError, match="between 50 and 5000"):
        cp.compare_with_model(data, RATES, reps=6000)
    with pytest.raises(ValueError, match="sample_offset"):
        cp.sorting_under_model(data, RATES, reps=600)
    with pytest.raises(ValueError, match="10 to 100 confirming"):
        cp.calibrate(data, confirm_reps=150)
